import "./globals.css";

export const metadata = {
  title: "Blokc-Internship",
  description: "Generated by create next app",
  icons: {
    icon: '/MetaMask_Icon.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen flex justify-center items-center w-full p-20">
        {children}
      </body>
    </html>
  );
}
